# Generated by Django 4.0.4 on 2022-06-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
